# Graph Representation in data structure

# For unweighted directed graph

## Adjacency matrix representation:

In [40]:
import numpy as np

In [41]:
0  # int
0.  # float
0 == 0.

0

0.0

True

In [42]:
[[0.]]

[[0.0]]

In [43]:
np.zeros(shape=(5, 5))  # shape=(rows, cols)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
V = [0, 1, 2, 3, 4]
E = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]

### Using NumPy 2d array

In [45]:
size = len(V)
adjacency_matrix = np.zeros(shape=(size, size))  # skeleton [using numpy array]

for (i, j) in E:
  adjacency_matrix[i, j] = 1

adjacency_matrix

array([[0., 1., 1., 0., 0.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

### Using Python nested list

In [46]:
size = len(V)
adjacency_matrix = [[0 for j in range(size)] for i in range(size)]  # skeleton [using py 2d list]

for (i, j) in E:
  adjacency_matrix[i][j] = 1

adjacency_matrix

[[0, 1, 1, 0, 0],
 [0, 0, 0, 1, 1],
 [0, 0, 0, 1, 1],
 [0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0]]

## Adjacency list representation:

In [47]:
V = [0, 1, 2, 3, 4]
E = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]

In [48]:
adjacency_list = {}
size = len(V)

for i in range(size):
  adjacency_list[i] = []

for (i, j) in E:
  adjacency_list[i].append(j)

adjacency_list

{0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}

# For unweighted undirected graph

In [49]:
V = [0, 1, 2, 3, 4]
E = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]  # original edges
UE = E + [(j, i) for (i, j) in E]  # original + reversed (UE: undirected edges)

In [50]:
E  # original edges
[(j, i) for (i, j) in E]  # reversed edges

print(E + [(j, i) for (i, j) in E])  # original + reversed

[(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]

[(1, 0), (2, 0), (3, 1), (4, 1), (4, 2), (3, 2), (4, 3)]

[(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4), (1, 0), (2, 0), (3, 1), (4, 1), (4, 2), (3, 2), (4, 3)]


In [51]:
adjacency_list = {}
size = len(V)

for i in range(size):
  adjacency_list[i] = []
for (i, j) in UE:
  adjacency_list[i].append(j)

adjacency_list

{0: [1, 2], 1: [3, 4, 0], 2: [4, 3, 0], 3: [4, 1, 2], 4: [1, 2, 3]}

In [52]:
size = len(V)
adjacency_matrix = np.zeros(shape=(size, size))

for (i, j) in UE:
  adjacency_matrix[i, j] = 1

adjacency_matrix

array([[0., 1., 1., 0., 0.],
       [1., 0., 0., 1., 1.],
       [1., 0., 0., 1., 1.],
       [0., 1., 1., 0., 1.],
       [0., 1., 1., 1., 0.]])

In [53]:
size = len(V)
adjacency_matrix = [[0 for j in range(size)] for i in range(size)]  # skeleton

for (i, j) in UE:
  adjacency_matrix[i][j] = 1

adjacency_matrix

[[0, 1, 1, 0, 0],
 [1, 0, 0, 1, 1],
 [1, 0, 0, 1, 1],
 [0, 1, 1, 0, 1],
 [0, 1, 1, 1, 0]]

# Breadth First Search(BFS) 

In [54]:
class Queue:
  def __init__(self):
    self.data = []

  def is_empty(self):
    return len(self.data) == 0

  def enqueue(self, value):
    self.data.append(value)

  def dequeue(self):
    if self.is_empty():
      raise Exception('queue is empty')
    return self.data.pop(0)

  def __str__(self):
    return str(self.data)


queue = Queue()
queue.enqueue(10)
queue.enqueue(20)
queue.enqueue(30)

print(queue.dequeue())
print(queue.dequeue())
queue.enqueue(40)
print(queue.dequeue())
print(queue.dequeue())
print(queue)

10
20
30
40
[]


## Implementation BFS for adjacency list

In [55]:
def bfs_adjacency_list(adjacency_list, start_vertex):
  visited = {}
  for vertex in adjacency_list:
    visited[vertex] = False
  # print(f'{visited=}')

  queue = Queue()
  queue.enqueue(start_vertex)
  visited[start_vertex] = True

  while not queue.is_empty():
    curr_vertex = queue.dequeue()
    neighbors = adjacency_list[curr_vertex]
    for adj_vertex in neighbors:
      if visited[adj_vertex]:
        continue
      queue.enqueue(adj_vertex)
      visited[adj_vertex] = True

  return visited


adjacency_list = {0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}
bfs_adjacency_list(adjacency_list, 0)

{0: True, 1: True, 2: True, 3: True, 4: True}

## Implementation BFS for adjacency matrix

In [56]:
V = [0, 1, 2, 3, 4]
E = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]
size = len(V)
adjacency_matrix = np.zeros(shape=(size, size))

for (i, j) in E:
  adjacency_matrix[i, j] = 1

# rows, cols = adjacency_matrix.shape
# print(rows, cols)
adjacency_matrix

array([[0., 1., 1., 0., 0.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [57]:
def get_neighbors(adjacency_matrix, vertex):
  neighbors = []
  rows, cols = adjacency_matrix.shape
  for j in range(cols):
    if adjacency_matrix[vertex, j] == 1:
      neighbors.append(j)
  return neighbors


get_neighbors(adjacency_matrix, 0)

[1, 2]

In [58]:
def bfs_adjacency_matrix(adjacency_matrix, start_vertex):
  visited = {}
  rows, cols = adjacency_matrix.shape
  for i in range(rows):
    visited[i] = False
  # print(f'{visited=}')

  queue = Queue()
  queue.enqueue(start_vertex)
  visited[start_vertex] = True

  while not queue.is_empty():
    curr_vertex = queue.dequeue()
    neighbors = get_neighbors(adjacency_matrix, curr_vertex)
    for adj_vertex in neighbors:
      if visited[adj_vertex]:
        continue
      queue.enqueue(adj_vertex)
      visited[adj_vertex] = True

  return visited


bfs_adjacency_matrix(adjacency_matrix, 0)

{0: True, 1: True, 2: True, 3: True, 4: True}

## Find [traversal order] using BFS

In [59]:
def bfs_traversal_order(adjacency_list, start_vertex):
  visited = {}
  for vertex in adjacency_list:
    visited[vertex] = False

  queue = Queue()
  queue.enqueue(start_vertex)
  visited[start_vertex] = True
  traversal_order = [start_vertex]

  while not queue.is_empty():
    curr_vertex = queue.dequeue()
    neighbors = adjacency_list[curr_vertex]
    for adj_vertex in neighbors:
      if visited[adj_vertex]:
        continue
      queue.enqueue(adj_vertex)
      visited[adj_vertex] = True
      traversal_order.append(adj_vertex)
      # print(f'{adj_vertex=}')

  return (visited, traversal_order)


adjacency_list = {0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}
bfs_traversal_order(adjacency_list, 0)

({0: True, 1: True, 2: True, 3: True, 4: True}, [0, 1, 2, 3, 4])

## Find parent of each vertex using BFS

In [60]:
def bfs_parent(adjacency_list, start_vertex):
  visited = {}
  parent = {}
  for vertex in adjacency_list:
    visited[vertex] = False
    parent[vertex] = -1
  # print(f'{visited=}, {parent=}')

  queue = Queue()
  queue.enqueue(start_vertex)
  visited[start_vertex] = True

  while not queue.is_empty():
    curr_vertex = queue.dequeue()
    neighbors = adjacency_list[curr_vertex]
    for adj_vertex in neighbors:
      if visited[adj_vertex]:
        continue
      queue.enqueue(adj_vertex)
      visited[adj_vertex] = True
      parent[adj_vertex] = curr_vertex
      # print(f'{adj_vertex=}, {curr_vertex=}')

  return (visited, parent)


adjacency_list = {0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}
bfs_parent(adjacency_list, 0)

({0: True, 1: True, 2: True, 3: True, 4: True},
 {0: -1, 1: 0, 2: 0, 3: 1, 4: 1})

## Find level number of vertices using BFS

In [61]:
def bfs_level(adjacency_list, start_vertex):
  parent = {}
  level = {}
  for vertex in adjacency_list:
    parent[vertex] = -1
    level[vertex] = -1

  queue = Queue()
  queue.enqueue(start_vertex)
  level[start_vertex] = 0

  while not queue.is_empty():
    curr_vertex = queue.dequeue()
    neighbors = adjacency_list[curr_vertex]
    for adj_vertex in neighbors:
      if level[adj_vertex] == -1:
        queue.enqueue(adj_vertex)
        parent[adj_vertex] = curr_vertex
        level[adj_vertex] = level[curr_vertex]+1

  return (parent, level)


adjacency_list = {0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}
bfs_level(adjacency_list, 0)

({0: -1, 1: 0, 2: 0, 3: 1, 4: 1}, {0: 0, 1: 1, 2: 1, 3: 2, 4: 2})

# Depth First Search(DFS)

## Implementation of DFS for adjacency list

### DFS for adjacency list [using Stack]

In [62]:
class Stack:
  def __init__(self):
    self.data = []

  def is_empty(self):
    return len(self.data) == 0

  def push(self, value):
    self.data.append(value)

  def pop(self):
    if self.is_empty():
      raise Exception('stack is empty')
    return self.data.pop()

  def __str__(self):
    return str(self.data)


stack = Stack()
stack.push(10)
stack.push(20)
stack.push(30)

print(stack.pop())
print(stack.pop())
stack.push(40)
print(stack.pop())
print(stack)

30
20
40
[10]


In [63]:
# if num is even -> print its square, if odd then do nothing
def print_even_squares(num):
  if num % 2 == 1:  # check stop condition [early return]
    return
  print(num ** 2)

  # if num % 2 == 0:  # check ok condition
  #   print(num ** 2)


print_even_squares(11)

In [115]:
# if not visited[curr_vertex]: # check ok condition ✅
#     all safe here (inside `if`) ✌️
#     visited[curr_vertex] = True
#     do step 1
#     do step 2

# if visited[curr_vertex]: # check stop condition ⚠️
#     continue # early return, avoid danger 🤗
# all safe here (outside `if`) ✌️
# visited[curr_vertex] = True
# do step 1
# do step 2

In [65]:
def dfs_adjacency_list(adjacency_list, start_vertex):
  visited = {}
  for vertex in adjacency_list:
    visited[vertex] = False
  # print(f'{visited=}')

  stack = Stack()
  stack.push(start_vertex)

  while not stack.is_empty():
    curr_vertex = stack.pop()  # u
    if visited[curr_vertex]:
      continue  # avoid danger 🤗
    visited[curr_vertex] = True

    neighbors = adjacency_list[curr_vertex]
    for adj_vertex in neighbors:  # v
      if not visited[adj_vertex]:
        stack.push(adj_vertex)

  return visited


adjacency_list = {0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}
dfs_adjacency_list(adjacency_list, 0)

{0: True, 1: True, 2: True, 3: True, 4: True}

### DFS for adjacency list [recursive, without stack]

In [92]:
def init_dfs_recursive(adjacency_list):
  visited = {}
  for vertex in adjacency_list:
    visited[vertex] = False
  return visited

In [110]:
# using global variable `visited`

def dfs_adjacency_list_recursive(adjacency_list, curr_vertex):
  visited[curr_vertex] = True  # `visited` is defined outside this function

  neighbors = adjacency_list[curr_vertex]
  for adj_vertex in neighbors:
    if not visited[adj_vertex]:
      dfs_adjacency_list_recursive(adjacency_list, adj_vertex)


# test code
adjacency_list = {0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}
visited = init_dfs_recursive(adjacency_list)  # `visited` is defined here
dfs_adjacency_list_recursive(adjacency_list, 0)  # no `visited` parameter
print(visited)  # we print `visited` after recursion finishes

{0: True, 1: True, 2: True, 3: True, 4: True}


In [112]:
# using `visited` parameter, NOT using global variable

def dfs_adjacency_list_recursive(adjacency_list, curr_vertex, visited):
  visited[curr_vertex] = True  # `visited` is taken as a parameter

  neighbors = adjacency_list[curr_vertex]
  for adj_vertex in neighbors:
    if not visited[adj_vertex]:
      visited = dfs_adjacency_list_recursive(adjacency_list, adj_vertex, visited)
  return visited


# test code
adjacency_list = {0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}
visited = init_dfs_recursive(adjacency_list)  # `visited` is defined here
dfs_adjacency_list_recursive(adjacency_list, 0, visited)  # we give `visited` parameter

{0: True, 1: True, 2: True, 3: True, 4: True}

## Implementation of DFS for adjacency matrix

### DFS for adjacency matrix [using Stack]

In [68]:
def dfs_adjacency_matrix(adjacency_matrix, start_vertex):
  pass


dfs_adjacency_matrix(adjacency_matrix, 0)