# Graph Representation in data structure

# For unweighted directed graph

## Adjacency matrix representation:

In [4]:
import numpy as np

In [5]:
0  # int
0.  # float
0 == 0.

0

0.0

True

In [6]:
[[0.]]

[[0.0]]

In [7]:
np.zeros(shape=(5, 5))  # shape=(rows, cols)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
V = [0, 1, 2, 3, 4]
E = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]

### Using NumPy 2d array

In [9]:
size = len(V)
adjacency_matrix = np.zeros(shape=(size, size))  # skeleton [using numpy array]

for (i, j) in E:
  adjacency_matrix[i, j] = 1

adjacency_matrix

array([[0., 1., 1., 0., 0.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

### Using Python nested list

In [10]:
size = len(V)
adjacency_matrix = [[0 for j in range(size)] for i in range(size)]  # skeleton [using py 2d list]

for (i, j) in E:
  adjacency_matrix[i][j] = 1

adjacency_matrix

[[0, 1, 1, 0, 0],
 [0, 0, 0, 1, 1],
 [0, 0, 0, 1, 1],
 [0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0]]

## Adjacency list representation:

In [11]:
V = [0, 1, 2, 3, 4]
E = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]

In [12]:
adjacency_list = {}
size = len(V)

for i in range(size):
  adjacency_list[i] = []

for (i, j) in E:
  adjacency_list[i].append(j)

adjacency_list

{0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}

# For unweighted undirected graph

In [13]:
V = [0, 1, 2, 3, 4]
E = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]  # original edges
UE = E + [(j, i) for (i, j) in E]  # original + reversed (UE: undirected edges)

In [14]:
E  # original edges
[(j, i) for (i, j) in E]  # reversed edges

print(E + [(j, i) for (i, j) in E])  # original + reversed

[(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]

[(1, 0), (2, 0), (3, 1), (4, 1), (4, 2), (3, 2), (4, 3)]

[(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4), (1, 0), (2, 0), (3, 1), (4, 1), (4, 2), (3, 2), (4, 3)]


In [15]:
adjacency_list = {}
size = len(V)

for i in range(size):
  adjacency_list[i] = []
for (i, j) in UE:
  adjacency_list[i].append(j)

adjacency_list

{0: [1, 2], 1: [3, 4, 0], 2: [4, 3, 0], 3: [4, 1, 2], 4: [1, 2, 3]}

In [16]:
size = len(V)
adjacency_matrix = np.zeros(shape=(size, size))

for (i, j) in UE:
  adjacency_matrix[i, j] = 1

adjacency_matrix

array([[0., 1., 1., 0., 0.],
       [1., 0., 0., 1., 1.],
       [1., 0., 0., 1., 1.],
       [0., 1., 1., 0., 1.],
       [0., 1., 1., 1., 0.]])

In [17]:
size = len(V)
adjacency_matrix = [[0 for j in range(size)] for i in range(size)]  # skeleton

for (i, j) in UE:
  adjacency_matrix[i][j] = 1

adjacency_matrix

[[0, 1, 1, 0, 0],
 [1, 0, 0, 1, 1],
 [1, 0, 0, 1, 1],
 [0, 1, 1, 0, 1],
 [0, 1, 1, 1, 0]]

# Breadth First Search(BFS) 

In [18]:
class Queue:
  def __init__(self):
    self.data = []

  def is_empty(self):
    return len(self.data) == 0

  def enqueue(self, value):
    self.data.append(value)

  def dequeue(self):
    if self.is_empty():
      raise Exception('queue is empty')
    return self.data.pop(0)

  def __str__(self):
    return str(self.data)


queue = Queue()
queue.enqueue(10)
queue.enqueue(20)
queue.enqueue(30)

print(queue.dequeue())
print(queue.dequeue())
queue.enqueue(40)
print(queue.dequeue())
print(queue.dequeue())
print(queue)

10
20
30
40
[]


## Implementation BFS for adjacency list

In [19]:
def bfs_adjacency_list(adjacency_list, start_vertex):
  visited = {}
  for vertex in adjacency_list:
    visited[vertex] = False
  # print(f'{visited=}')

  queue = Queue()
  queue.enqueue(start_vertex)
  visited[start_vertex] = True

  while not queue.is_empty():
    curr_vertex = queue.dequeue()
    neighbors = adjacency_list[curr_vertex]
    for adj_vertex in neighbors:
      if visited[adj_vertex]:
        continue
      queue.enqueue(adj_vertex)
      visited[adj_vertex] = True

  return visited


adjacency_list = {0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}
bfs_adjacency_list(adjacency_list, 0)

{0: True, 1: True, 2: True, 3: True, 4: True}

## Implementation BFS for adjacency matrix

In [20]:
V = [0, 1, 2, 3, 4]
E = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]
size = len(V)
adjacency_matrix = np.zeros(shape=(size, size))

for (i, j) in E:
  adjacency_matrix[i, j] = 1

# rows, cols = adjacency_matrix.shape
# print(rows, cols)
adjacency_matrix

array([[0., 1., 1., 0., 0.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [21]:
def get_neighbors(adjacency_matrix, vertex):
  neighbors = []
  rows, cols = adjacency_matrix.shape
  for j in range(cols):
    if adjacency_matrix[vertex, j] == 1:
      neighbors.append(j)
  return neighbors


get_neighbors(adjacency_matrix, 0)

[1, 2]

In [22]:
def bfs_adjacency_matrix(adjacency_matrix, start_vertex):
  visited = {}
  rows, cols = adjacency_matrix.shape
  for i in range(rows):
    visited[i] = False
  # print(f'{visited=}')

  queue = Queue()
  queue.enqueue(start_vertex)
  visited[start_vertex] = True

  while not queue.is_empty():
    curr_vertex = queue.dequeue()
    neighbors = get_neighbors(adjacency_matrix, curr_vertex)
    for adj_vertex in neighbors:
      if visited[adj_vertex]:
        continue
      queue.enqueue(adj_vertex)
      visited[adj_vertex] = True

  return visited


bfs_adjacency_matrix(adjacency_matrix, 0)

{0: True, 1: True, 2: True, 3: True, 4: True}

## Find [traversal order] using BFS

In [38]:
def bfs_traversal_order(adjacency_list, start_vertex):
  visited = {}
  for vertex in adjacency_list:
    visited[vertex] = False

  queue = Queue()
  queue.enqueue(start_vertex)
  visited[start_vertex] = True
  traversal_order = [start_vertex]

  while not queue.is_empty():
    curr_vertex = queue.dequeue()
    neighbors = adjacency_list[curr_vertex]
    for adj_vertex in neighbors:
      if visited[adj_vertex]:
        continue
      queue.enqueue(adj_vertex)
      visited[adj_vertex] = True
      traversal_order.append(adj_vertex)
      # print(f'{adj_vertex=}')

  return (visited, traversal_order)


adjacency_list = {0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}
bfs_traversal_order(adjacency_list, 0)

({0: True, 1: True, 2: True, 3: True, 4: True}, [0, 1, 2, 3, 4])

## Find parent of each vertex using BFS

In [31]:
def bfs_parent(adjacency_list, start_vertex):
  visited = {}
  parent = {}
  for vertex in adjacency_list:
    visited[vertex] = False
    parent[vertex] = -1
  # print(f'{visited=}, {parent=}')

  queue = Queue()
  queue.enqueue(start_vertex)
  visited[start_vertex] = True

  while not queue.is_empty():
    curr_vertex = queue.dequeue()
    neighbors = adjacency_list[curr_vertex]
    for adj_vertex in neighbors:
      if visited[adj_vertex]:
        continue
      queue.enqueue(adj_vertex)
      visited[adj_vertex] = True
      parent[adj_vertex] = curr_vertex
      # print(f'{adj_vertex=}, {curr_vertex=}')

  return (visited, parent)


adjacency_list = {0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}
bfs_parent(adjacency_list, 0)

({0: True, 1: True, 2: True, 3: True, 4: True},
 {0: -1, 1: 0, 2: 0, 3: 1, 4: 1})

## Find level number of vertices using BFS

In [49]:
def bfs_level(adjacency_list, start_vertex):
  parent = {}
  level = {}
  for vertex in adjacency_list:
    parent[vertex] = -1
    level[vertex] = -1

  queue = Queue()
  queue.enqueue(start_vertex)
  level[start_vertex] = 0

  while not queue.is_empty():
    curr_vertex = queue.dequeue()
    neighbors = adjacency_list[curr_vertex]
    for adj_vertex in neighbors:
      if level[adj_vertex] == -1:
        queue.enqueue(adj_vertex)
        parent[adj_vertex] = curr_vertex
        level[adj_vertex] = level[curr_vertex]+1

  return (parent, level)


adjacency_list = {0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}
bfs_level(adjacency_list, 0)

({0: -1, 1: 0, 2: 0, 3: 1, 4: 1}, {0: 0, 1: 1, 2: 1, 3: 2, 4: 2})