# Graph Representation in data structure

## For unweighted directed graph

In [1]:
import numpy as np

In [2]:
V = [0, 1, 2, 3, 4]
E = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]

In [20]:
size = len(V)
adjacency_matrix = np.zeros(shape=(size, size))

adjacency_matrix  # skeleton matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
size = len(V)
adjacency_matrix = [[0 for _ in range(size)] for _ in range(size)]

adjacency_matrix  # skeleton matrix

[[0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0]]

### adjacency_matrix: np array

In [14]:
size = len(V)
adjacency_matrix = np.zeros(shape=(size, size))

for (i, j) in E:
  adjacency_matrix[i, j] = 1

adjacency_matrix

array([[0., 1., 1., 0., 0.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

### adjacency_matrix: python nested list

In [19]:
size = len(V)
adjacency_matrix = [[0 for _ in range(size)] for _ in range(size)]

for (i, j) in E:
  adjacency_matrix[i][j] = 1

adjacency_matrix

[[0, 1, 1, 0, 0],
 [0, 0, 0, 1, 1],
 [0, 0, 0, 1, 1],
 [0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0]]

### adjacency_list: python dictionary

In [22]:
size = len(V)
adjacency_list = {}

for i in range(size):
  adjacency_list[i] = []

adjacency_list

{0: [], 1: [], 2: [], 3: [], 4: []}

In [23]:
size = len(V)
adjacency_list = {}

for i in range(size):
  adjacency_list[i] = []
for (i, j) in E:
  adjacency_list[i].append(j)

adjacency_list

{0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}

In [28]:
size = len(V)
adjacency_list = {}

for (i, j) in E:
  if i not in adjacency_list:
    adjacency_list[i] = []
  adjacency_list[i].append(j)

adjacency_list

{0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4]}

## For unweighted undirected graph

In [35]:
V = [0, 1, 2, 3, 4]
E = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]

print(E)  # original edges
print([(j, i) for (i, j) in E])  # reversed edges

[(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]
[(1, 0), (2, 0), (3, 1), (4, 1), (4, 2), (3, 2), (4, 3)]


In [38]:
UE = E + [(j, i) for (i, j) in E]  # original + reversed
print(UE)

[(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4), (1, 0), (2, 0), (3, 1), (4, 1), (4, 2), (3, 2), (4, 3)]


# Breadth First Search(BFS) 

In [51]:
class Queue:
  def __init__(self):
    self.data = []

  def is_empty(self):
    return len(self.data) == 0

  def enqueue(self, value):
    self.data.append(value)

  def dequeue(self):
    if self.is_empty():
      return
    return self.data.pop(0)

  def __str__(self):
    return str(self.data)


queue = Queue()
queue.enqueue(10)
queue.enqueue(20)
queue.enqueue(30)
print(queue.dequeue())
print(queue.dequeue())
queue.enqueue(40)
print(queue.dequeue())

print(queue)

10
20
30
[40]


## Implementation BFS for adjacency list

In [63]:
def bfs_adjacency_list(adjacency_list, start_vertex):
  visited = {}
  for vertex in adjacency_list:
    visited[vertex] = False
  # print(f'{visited=}')

  queue = Queue()
  queue.enqueue(start_vertex)
  visited[start_vertex] = True

  while not queue.is_empty():
    curr_vertex = queue.dequeue()
    neighbors = adjacency_list[curr_vertex]
    for adj_vertex in neighbors:
      if visited[adj_vertex]:
        continue
      queue.enqueue(adj_vertex)
      visited[adj_vertex] = True

  return visited


adjacency_list = {0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}
bfs_adjacency_list(adjacency_list, 0)

{0: True, 1: True, 2: True, 3: True, 4: True}

## Implementation BFS for adjacency matrix

In [77]:
V = [0, 1, 2, 3, 4]
E = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]

size = len(V)
adjacency_matrix = np.zeros(shape=(size, size))
for (i, j) in E:
  adjacency_matrix[i, j] = 1

adjacency_matrix

array([[0., 1., 1., 0., 0.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [87]:
def get_neighbors(adjacency_matrix, vertex):
  rows, cols = adjacency_matrix.shape
  neighbors = []
  for j in range(cols):
    if adjacency_matrix[vertex, j] == 1:
      neighbors.append(j)
  return neighbors


get_neighbors(adjacency_matrix, 0)

[1, 2]

In [92]:
def bfs_adjacency_matrix(adjacency_matrix, start_vertex):
  rows, cols = adjacency_matrix.shape
  visited = {}
  for i in range(rows):
    visited[i] = False
  # print(f'{visited=}')

  queue = Queue()
  queue.enqueue(start_vertex)
  visited[start_vertex] = True

  while not queue.is_empty():
    curr_vertex = queue.dequeue()
    neighbors = get_neighbors(adjacency_matrix, curr_vertex)
    for adj_vertex in neighbors:
      if visited[adj_vertex]:
        continue
      queue.enqueue(adj_vertex)
      visited[adj_vertex] = True

  return visited


bfs_adjacency_matrix(adjacency_matrix, 0)

{0: True, 1: True, 2: True, 3: True, 4: True}

## Find parent of each vertex using BFS

In [117]:
def bfs_parent(adjacency_list, start_vertex):
  visited, parent = {}, {}
  for vertex in adjacency_list:
    visited[vertex] = False
    parent[vertex] = -1
  # print(f'{visited=}, {parent=}')

  queue = Queue()
  queue.enqueue(start_vertex)
  visited[start_vertex] = True

  while not queue.is_empty():
    curr_vertex = queue.dequeue()
    neighbors = adjacency_list[curr_vertex]
    for adj_vertex in neighbors:
      if visited[adj_vertex]:
        continue
      queue.enqueue(adj_vertex)
      visited[adj_vertex] = True
      parent[adj_vertex] = curr_vertex

  return (visited, parent)


adjacency_list = {0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}
bfs_parent(adjacency_list, 0)

({0: True, 1: True, 2: True, 3: True, 4: True},
 {0: -1, 1: 0, 2: 0, 3: 1, 4: 1})

## Find level number of vertices using BFS

In [126]:
def bfs_level(adjacency_list, start_vertex):
  level, parent = {}, {}
  for vertex in adjacency_list:
    level[vertex] = -1  # -1 means NOT visited
    parent[vertex] = -1

  queue = Queue()
  queue.enqueue(start_vertex)
  level[start_vertex] = 0

  while not queue.is_empty():
    curr_vertex = queue.dequeue()
    neighbors = adjacency_list[curr_vertex]
    for adj_vertex in neighbors:
      if level[adj_vertex] != -1:  # skip if already visited
        continue
      queue.enqueue(adj_vertex)
      level[adj_vertex] = level[curr_vertex] + 1
      parent[adj_vertex] = curr_vertex

  return (level, parent)


adjacency_list = {0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}

# ({0: 0, 1: 1, 2: 1, 3: 2, 4: 2}, {0: -1, 1: 0, 2: 0, 3: 1, 4: 1})
bfs_level(adjacency_list, 0)

({0: 0, 1: 1, 2: 1, 3: 2, 4: 2}, {0: -1, 1: 0, 2: 0, 3: 1, 4: 1})

# Depth First Search(DFS)